export const ENCRYPTED_ROOT = ".obsidian-github-sync-encrypted";
export const ENCRYPTED_CONFIG_PATH = `${ENCRYPTED_ROOT}/config.json`;
export const ENCRYPTED_MANIFEST_PATH = `${ENCRYPTED_ROOT}/manifest.enc`;
export const ENCRYPTED_OBJECTS_ROOT = `${ENCRYPTED_ROOT}/objects`;
export const ENCRYPTED_FORMAT_VERSION = 1;
export const ENCRYPTED_INDEX_MODE = "single";
export const AES_GCM_NONCE_BYTES = 12;
export const OBJECT_ID_BYTES = 24;
export const MAX_ENCRYPTED_FILE_SIZE = 5 * 1024 * 1024 * 1024;

export const GITHUB_RECOMMENDED_MAX_BYTES = 50 * 1024 * 1024;
export const ENCRYPTED_CHUNK_PLAINTEXT_BYTES = 24 * 1024 * 1024;
export const ENCRYPTED_PACKS_ROOT = `${ENCRYPTED_ROOT}/packs`;
export const ENCRYPTED_PACK_PLAINTEXT_BYTES = 32 * 1024 * 1024;
export const ENCRYPTED_PACK_MAX_FILES = 1000;
export const ENCRYPTED_PACK_MODE_FILE_COUNT_THRESHOLD = 1000;
export const ENCRYPTED_PACK_MODE_TOTAL_BYTES_THRESHOLD = 1024 * 1024 * 1024;
